default_language_version:
  python: python3

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  - repo: local
    hooks:
      - id: file-format
        name: file-format
        language: python
        entry: python .github/workflows/file_format.py
        types_or: [text]
